#!/bin/bash

version=$1

if [ -z "$version" ]; then
    echo -e "Usage: ./version <version>\n\ne.g. ./version 1.2.3-rc1"
    exit;
fi

# Version without suffix. E.g. 1.2.3-rc1 becomes 1.2.3
version_info=$(echo $1 | sed 's/-.*//')

# Save any open work
stash_name="pre-$version"
stash_result=`git stash save $stash_name`

csproj=src/Perplex.ContentBlocks/Perplex.ContentBlocks.csproj
csprojCore=src/Perplex.ContentBlocks.Core/Perplex.ContentBlocks.Core.csproj

# Update versions
sed -i "s/<\(Version\)>.*<\/\1>/<\1>$version<\/\1>/" $csproj
sed -i "s/<\(Version\)>.*<\/\1>/<\1>$version<\/\1>/" $csprojCore

# Add
git add $csproj > /dev/null 2>&1
git add $csprojCore > /dev/null 2>&1

# Commit
git commit -m "Version ${version}" > /dev/null 2>&1

# Restore previous work -- if any
if [ "$(echo $stash_result | grep $stash_name)" ]; then
    git stash pop --index > /dev/null 2>&1
fi
